// ─── 类型统一入口（Re-export Hub） ─────────────────────
// 按业务模块拆分类型定义，此处统一导出
//
// 新增模块时：
// 1. 创建 src/types/xxx.ts
// 2. 在此处 export

export type { AppConfig } from "./config";
export type { SystemInfo } from "./system";
export type {
  AiUnrestrictedState,
  EnableAiUnrestrictedInput,
  SystemCloseBehavior,
  SystemLanguage,
  SystemLogLevel,
  SystemPlatform,
  SystemSettings,
  SystemSettingsExportResult,
  UpdateSystemSettingsInput,
} from "./systemSettings";
export type {
  AiProvider,
  AiProviderAskInput,
  AiProviderAskResult,
  AiProviderModelListInput,
  AiProviderModelListResult,
  AiProviderRegion,
  AiProviderRoute,
  AiProviderStatus,
  AiProviderTestResult,
  UpsertAiProviderInput,
  UpsertAiProviderRouteInput,
} from "./aiProvider";
export type {
  AiExperience,
  AiExperienceMatch,
  AiExperienceRecallInput,
  AiRunbook,
  AiRunbookRunResult,
  AiRunbookStep,
  AiRunbookStepResult,
  AiSkill,
  AiSkillMatch,
  AiSkillPromptPreviewInput,
  AiSkillPromptPreviewResult,
  AiSkillScope,
  AiSkillSource,
  AiSkillStats,
  AiSkillTriggerInput,
  AiSkillTriggerResult,
  ListAiSkillsInput,
  ListAiSkillsResult,
  RunAiRunbookInput,
  SyncBuiltinAiSkillsResult,
  UpsertAiExperienceInput,
  UpsertAiRunbookInput,
  UpsertAiSkillInput,
} from "./aiSkill";
export type {
  SshConfigImportResult,
  SshServer,
  SshServerAuthType,
  SshServerConnectionTestInput,
  SshServerPolicy,
  SshServerSource,
  SshServerStatus,
  SshServerTestResult,
  UpsertSshServerInput,
} from "./sshServer";
export type {
  AuthorizeCredentialInput,
  CredentialStatus,
  CredentialType,
  CredentialVaultItem,
  RotateCredentialInput,
  UpsertCredentialInput,
} from "./credentialVault";
export type {
  ListSecureCredentialsInput,
  CreateSecureCredentialSessionInput,
  ListSecureCredentialSessionsInput,
  RotateSecureCredentialInput,
  SecureCredential,
  SecureCredentialApprovalPolicy,
  SecureCredentialAuditLog,
  SecureCredentialGitReadInput,
  SecureCredentialGitWriteInput,
  SecureCredentialGitWriteOperation,
  SecureCredentialGitWriteResult,
  SecureCredentialHttpRequestInput,
  SecureCredentialHttpRequestResult,
  SecureCredentialHttpWriteInput,
  SecureCredentialOverview,
  SecureCredentialPolicySettings,
  SecureCredentialProvider,
  SecureCredentialProviderReadResult,
  SecureCredentialProviderTestInput,
  SecureCredentialProviderTestResult,
  SecureCredentialRepository,
  SecureCredentialRepositoryListInput,
  SecureCredentialSession,
  SecureCredentialSessionStatus,
  SecureCredentialSessionStatusValue,
  SecureCredentialStatus,
  SecureCredentialType,
  SetSecureCredentialEnabledInput,
  ListSecureCredentialAuditLogsInput,
  UpdateSecureCredentialPolicySettingsInput,
  UpsertSecureCredentialInput,
} from "./secureCredential";
export type {
  AiCommitGitWorkspaceInput,
  AiCommitGitWorkspaceResult,
  GitWorkspace,
  GitWorkspaceBranch,
  GitWorkspaceDetail,
  GitWorkspaceScanJobStatus,
  GitWorkspaceScanStartResult,
  GitWorkspaceStatus,
  ListGitWorkspacesInput,
  MergeGitWorkspaceBranchInput,
  ScanGitWorkspaceRootInput,
  ScanGitWorkspaceRootResult,
  SwitchGitWorkspaceBranchInput,
  UpsertGitWorkspaceInput,
} from "./gitWorkspace";
export type {
  DatabaseAuthType,
  DatabaseColumnSchema,
  DatabaseConnection,
  DatabaseConnectionMode,
  DatabaseConnectionStatus,
  DatabaseConnectionTestResult,
  DatabaseExportInput,
  DatabaseExportMode,
  DatabaseExportResult,
  DatabaseIndexSchema,
  DatabaseNameListInput,
  DatabaseNameListResult,
  DatabaseQueryInput,
  DatabaseQueryResult,
  DatabaseSchemaInput,
  DatabaseSchemaResult,
  DatabaseSecurityMode,
  DatabaseTableSchema,
  DatabaseType,
  RedisDatabaseInfo,
  RedisDatabaseListInput,
  RedisDatabaseListResult,
  RedisDescribeKeysInput,
  RedisKeyEntry,
  RedisKeyTreeInput,
  RedisKeyTreeResult,
  RedisScanInput,
  RedisScanResult,
  RedisValuePreview,
  RedisValuePreviewInput,
  UpsertDatabaseConnectionInput,
} from "./databaseOps";
export type {
  TerminalCommandInput,
  TerminalCommandResult,
  TerminalSessionCloseInput,
  TerminalSessionEvent,
  TerminalSessionResizeInput,
  TerminalSessionStartInput,
  TerminalSessionStartResult,
  TerminalSessionWriteInput,
} from "./terminal";
export type {
  SftpCreateDirectoryInput,
  SftpCreateFileInput,
  SftpDeleteInput,
  SftpFileEntry,
  SftpFileType,
  SftpListInput,
  SftpListResult,
  SftpOperationResult,
  SftpReadTextInput,
  SftpReadTextResult,
  SftpRenameInput,
  SftpTransferPathInput,
  SftpWriteTextInput,
} from "./sftp";
export type {
  ConfigureMcpClientInput,
  ConfigureMcpClientResult,
  McpClientConfig,
  McpManualSnippet,
  McpOverview,
  McpServerStatus,
  McpToolPermission,
} from "./mcp";
export type {
  ApprovalRequest,
  ApprovalRisk,
  ApprovalStatus,
  CreateApprovalRequestInput,
  DecideApprovalRequestInput,
  ListApprovalRequestsInput,
} from "./approval";
export type {
  JumpServerAiMode,
  JumpServerOpenResult,
  JumpServerProtocol,
  JumpServerSession,
  JumpServerStatus,
  UpsertJumpServerSessionInput,
} from "./jumpserver";
export type {
  AuditLog,
  AuditLogExportResult,
  AuditRisk,
  CreateAuditLogInput,
  ListAuditLogsInput,
} from "./audit";
export type {
  CollectResourceBatchInput,
  CollectResourceBatchResult,
  ListResourceAlertEventsInput,
  ListResourceAlertRulesInput,
  ResourceAlertEvent,
  ResourceAlertOperator,
  ResourceAlertRule,
  ResourceAlertSeverity,
  ResourceAlertStatus,
  ResourceMetricSnapshot,
  ResourceMonitorOverview,
  ResourceMonitorTarget,
  ResourceSnapshotListInput,
  ResourceStatus,
  ResourceTargetType,
  UpsertResourceAlertRuleInput,
  UpsertResourceMonitorTargetInput,
} from "./resourceMonitor";
export type {
  CreateDeploymentDryRunInput,
  CreateDeploymentRollbackDryRunInput,
  DeploymentAiAdviceInput,
  DeploymentAiAdviceResult,
  DeploymentCandidate,
  DeploymentDetectionResult,
  DeploymentEnvironmentProbe,
  DeploymentEnvironmentProfile,
  DeploymentGroup,
  DeploymentGroupTarget,
  DeploymentGroupTargetInput,
  DeploymentImageStoreApp,
  DeploymentImageStoreEnv,
  DeploymentPlan,
  DeploymentPlanStage,
  DeploymentProbeCheck,
  DeploymentRecipe,
  DeploymentRun,
  DeploymentRunDetail,
  DeploymentRunStep,
  DeploymentSourceType,
  DeploymentTarget,
  DeploymentTemplate,
  DetectDeploymentProjectInput,
  DockerBuildMode,
  ExecuteDeploymentRollbackInput,
  ExecuteDeploymentRunInput,
  InstallImageStoreAppInput,
  ListDeploymentRunsInput,
  UpsertDeploymentGroupInput,
  UpsertDeploymentTargetInput,
} from "./deployment";
