// ─── 类型统一入口（Re-export Hub） ─────────────────────
// 按业务模块拆分类型定义，此处统一导出
//
// 新增模块时：
// 1. 创建 src/types/xxx.ts
// 2. 在此处 export

export type { AppConfig } from "./config";
export type { SystemInfo } from "./system";
export type * from "./knowledge-domain";
export type {
  KnowledgeAskInput,
  KnowledgeAskResult,
  BuildKnowledgeEmbeddingBatchInput,
  KnowledgeRagContextPreview,
  KnowledgeRetrievalEvaluationCaseResult,
  KnowledgeRetrievalEvaluationRun,
  KnowledgeChunk,
  KnowledgeChunkEmbedding,
  KnowledgeChunkOptions,
  KnowledgeChunkWriteInput,
  KnowledgeCitation,
  KnowledgeCitationDetail,
  CaptureKnowledgeDirtyWorktreeSnapshotInput,
  CaptureKnowledgeGitSnapshotInput,
  CaptureKnowledgeLocalDirectorySnapshotInput,
  CreateKnowledgeCodeSnapshotInput,
  KnowledgeCodeFile,
  KnowledgeCodeFileContent,
  KnowledgeCodeAnalysisResult,
  KnowledgeCodeCallGraph,
  KnowledgeCodeCallGraphInput,
  KnowledgeCodeRelation,
  KnowledgeCodeFileChange,
  KnowledgeCodeSnapshotComparison,
  KnowledgeCodeSource,
  KnowledgeCodeSourceSettings,
  KnowledgeCodeSnapshot,
  KnowledgeCodeSymbol,
  SearchKnowledgeCodeSymbolsInput,
  CompareKnowledgeCodeSnapshotsInput,
  AnalyzeKnowledgeCodeImpactInput,
  KnowledgeDocument,
  KnowledgeDocumentDeletionImpactPreview,
  KnowledgeDocumentComparison,
  KnowledgeDocumentComparisonArtifact,
  KnowledgeDocumentDetail,
  KnowledgeDocumentVersion,
  RestoreKnowledgeDocumentResult,
  KnowledgeEmbeddingProfile,
  KnowledgeEmbeddingBatchResult,
  KnowledgeEmbeddingFingerprintInput,
  EstimateKnowledgeEmbeddingRebuildInput,
  KnowledgeEmbeddingIndexAvailability,
  KnowledgeEmbeddingIndexValidation,
  KnowledgeEmbeddingLifecycleResult,
  KnowledgeEmbeddingProfileTestResult,
  KnowledgeLocalEmbeddingCacheEntry,
  DownloadKnowledgeLocalEmbeddingModelInput,
  KnowledgeLocalEmbeddingDownloadProgress,
  GenerateKnowledgeLocalEmbeddingsInput,
  GenerateKnowledgeCodeDocumentsInput,
  GenerateKnowledgeCodeDocumentsResult,
  GenerateZentaoKnowledgeDocumentsInput,
  GenerateZentaoKnowledgeDocumentsResult,
  GenerateZentaoAiSummaryInput,
  GenerateZentaoAiSummaryResult,
  ImportKnowledgeExperiencesInput,
  ImportKnowledgeExperiencesResult,
  ImportKnowledgeLocalEmbeddingModelInput,
  ImportKnowledgeCommitRelationsInput,
  KnowledgeLocalEmbeddingModelImportResult,
  RemoveKnowledgeLocalEmbeddingModelInput,
  RunKnowledgeRetrievalEvaluationInput,
  KnowledgeLocalEmbeddingRuntimeStatus,
  KnowledgeEmbeddingRebuildEstimate,
  KnowledgeRemoteRebuildSourceEstimate,
  KnowledgeErrorDetail,
  KnowledgeFtsCapability,
  KnowledgeGenerationRun,
  KnowledgeGitRef,
  KnowledgeJob,
  KnowledgeJobProgress,
  KnowledgeListInput,
  KnowledgePage,
  KnowledgeParseAndChunkInput,
  KnowledgeParseAndChunkResult,
  KnowledgeParseInput,
  KnowledgeParsedBlock,
  KnowledgeParsedDocument,
  KnowledgeProject,
  KnowledgeQueryAnalysis,
  KnowledgeRelation,
  KnowledgeRelease,
  KnowledgeSearchHit,
  KnowledgeSearchInput,
  KnowledgeVectorSearchInput,
  KnowledgeSource,
  KnowledgeSourceScopeEntry,
  KnowledgeSourceScopePreview,
  KnowledgeSourceSyncResult,
  CompareKnowledgeDocumentVersionsInput,
  StartKnowledgeSourceSyncInput,
  SyncKnowledgeGitSourceInput,
  SyncKnowledgeLocalSourceInput,
  CreateKnowledgeDocumentVersionInput,
  UpsertKnowledgeEmbeddingProfileInput,
  UpsertKnowledgeDocumentInput,
  UpsertKnowledgeCodeSourceInput,
  UpsertKnowledgeProjectInput,
  UpsertKnowledgeReleaseInput,
  UpsertKnowledgeSourceInput,
  UpsertZentaoConnectionInput,
  UpsertZentaoProjectMappingInput,
  SyncZentaoMappingInput,
  ZentaoCapabilityProbeResult,
  ZentaoConnection,
  ZentaoEntity,
  ZentaoEntityRelation,
  ZentaoProjectMapping,
  ZentaoRemoteScopeItem,
  ZentaoSyncCursor,
  ZentaoSyncResult,
} from "./knowledge";
export type {
  AiUnrestrictedState,
  EnableAiUnrestrictedInput,
  SystemCloseBehavior,
  SystemLanguage,
  SystemLogLevel,
  SystemPlatform,
  SystemSettings,
  SystemSettingsExportResult,
  UpdateSystemSettingsInput,
} from "./systemSettings";
export type {
  AiProvider,
  AiProviderAskInput,
  AiProviderAskResult,
  AiProviderCapabilityMode,
  AiProviderModelListInput,
  AiProviderModelListResult,
  AiProviderRegion,
  AiProviderRoute,
  AiProviderStatus,
  AiProviderTestResult,
  UpsertAiProviderInput,
  UpsertAiProviderRouteInput,
} from "./aiProvider";
export type {
  AiExperience,
  AiExperienceMatch,
  AiExperienceRecallInput,
  AiRunbook,
  AiRunbookRunResult,
  AiRunbookStep,
  AiRunbookStepResult,
  AiSkill,
  AiSkillMatch,
  AiSkillPromptPreviewInput,
  AiSkillPromptPreviewResult,
  AiSkillScope,
  AiSkillSource,
  AiSkillStats,
  AiSkillTriggerInput,
  AiSkillTriggerResult,
  ListAiSkillsInput,
  ListAiSkillsResult,
  RunAiRunbookInput,
  SyncBuiltinAiSkillsResult,
  UpsertAiExperienceInput,
  UpsertAiRunbookInput,
  UpsertAiSkillInput,
} from "./aiSkill";
export type {
  SshConfigImportResult,
  SshServer,
  SshServerAuthType,
  SshServerConnectionTestInput,
  SshServerPolicy,
  SshServerSource,
  SshServerStatus,
  SshServerTestResult,
  UpsertSshServerInput,
} from "./sshServer";
export type {
  AuthorizeCredentialInput,
  CredentialStatus,
  CredentialType,
  CredentialVaultItem,
  RotateCredentialInput,
  UpsertCredentialInput,
} from "./credentialVault";
export type {
  ListSecureCredentialsInput,
  CreateSecureCredentialSessionInput,
  ListSecureCredentialSessionsInput,
  RotateSecureCredentialInput,
  SecureCredential,
  SecureCredentialApprovalPolicy,
  SecureCredentialAuditLog,
  SecureCredentialGitReadInput,
  SecureCredentialGitWriteInput,
  SecureCredentialGitWriteOperation,
  SecureCredentialGitWriteResult,
  SecureCredentialHttpRequestInput,
  SecureCredentialHttpRequestResult,
  SecureCredentialHttpWriteInput,
  SecureCredentialOverview,
  SecureCredentialPolicySettings,
  SecureCredentialProvider,
  SecureCredentialProviderReadResult,
  SecureCredentialProviderTestInput,
  SecureCredentialProviderTestResult,
  SecureCredentialRepository,
  SecureCredentialRepositoryListInput,
  SecureCredentialSession,
  SecureCredentialSessionStatus,
  SecureCredentialSessionStatusValue,
  SecureCredentialStatus,
  SecureCredentialType,
  SetSecureCredentialEnabledInput,
  ListSecureCredentialAuditLogsInput,
  UpdateSecureCredentialPolicySettingsInput,
  UpsertSecureCredentialInput,
} from "./secureCredential";
export type {
  AiCommitGitWorkspaceInput,
  AiCommitGitWorkspaceResult,
  CloneGitProviderRepositoriesInput,
  CommitGitWorkspaceInput,
  CommitGitWorkspaceResult,
  GitWorkspace,
  GitWorkspaceBranch,
  GitWorkspaceDetail,
  GitWorkspaceDiffInput,
  GitWorkspaceDiffResult,
  GitWorkspaceScanJobStatus,
  GitWorkspaceScanStartResult,
  GitWorkspaceStatus,
  GitWorkspaceStatusResult,
  ListGitWorkspacesInput,
  MergeGitWorkspaceBranchInput,
  ScanGitWorkspaceRootInput,
  ScanGitWorkspaceRootResult,
  StageGitWorkspaceFilesInput,
  SwitchGitWorkspaceBranchInput,
  UpsertGitWorkspaceInput,
} from "./gitWorkspace";
export type {
  CodeReviewBatchItem,
  CodeReviewBatchParseResult,
  CodeReviewChangedFile,
  CodeReviewCommit,
  CodeReviewPushStatus,
  CodeReviewRiskLevel,
  CodeReviewTask,
  CodeReviewTaskStatus,
  CreateCodeReviewBatchTaskItem,
  CreateCodeReviewBatchTasksInput,
  CreateCodeReviewTaskInput,
  ListCodeReviewTasksInput,
  ParseCodeReviewBatchInput,
  RunCodeReviewAiInput,
} from "./codeReview";
export type {
  DatabaseAuthType,
  DatabaseCellUpdateInput,
  DatabaseCellUpdateResult,
  DatabaseColumnSchema,
  DatabaseConnection,
  DatabaseConnectionMode,
  DatabaseConnectionStatus,
  DatabaseConnectionTestResult,
  DatabaseEditableQueryMeta,
  DatabaseExportInput,
  DatabaseExportMode,
  DatabaseExportResult,
  DatabaseIndexSchema,
  DatabaseNameListInput,
  DatabaseNameListResult,
  DatabaseQueryInput,
  DatabaseQueryResult,
  DatabaseSchemaInput,
  DatabaseSchemaResult,
  DatabaseSecurityMode,
  DatabaseTableSchema,
  DatabaseType,
  RedisDatabaseInfo,
  RedisDatabaseListInput,
  RedisDatabaseListResult,
  RedisDescribeKeysInput,
  RedisKeyEntry,
  RedisKeyTreeInput,
  RedisKeyTreeResult,
  RedisScanInput,
  RedisScanResult,
  RedisValuePreview,
  RedisValuePreviewInput,
  UpsertDatabaseConnectionInput,
} from "./databaseOps";
export type {
  TerminalCommandInput,
  TerminalCommandResult,
  TerminalSessionCloseInput,
  TerminalSessionEvent,
  TerminalSessionResizeInput,
  TerminalSessionStartInput,
  TerminalSessionStartResult,
  TerminalSessionWriteInput,
} from "./terminal";
export type {
  SftpCreateDirectoryInput,
  SftpCreateFileInput,
  SftpDeleteInput,
  SftpFileEntry,
  SftpFileType,
  SftpListInput,
  SftpListResult,
  SftpOperationResult,
  SftpReadTextInput,
  SftpReadTextResult,
  SftpRenameInput,
  SftpTransferPathInput,
  SftpWriteTextInput,
} from "./sftp";
export type {
  ConfigureMcpClientInput,
  ConfigureMcpClientResult,
  McpClientConfig,
  McpManualSnippet,
  McpOverview,
  McpServerStatus,
  McpToolPermission,
} from "./mcp";
export type {
  ApprovalRequest,
  ApprovalRisk,
  ApprovalStatus,
  CreateApprovalRequestInput,
  DecideApprovalRequestInput,
  ListApprovalRequestsInput,
} from "./approval";
export type {
  JumpServerAiMode,
  JumpServerOpenResult,
  JumpServerProtocol,
  JumpServerSession,
  JumpServerStatus,
  UpsertJumpServerSessionInput,
} from "./jumpserver";
export type {
  AuditLog,
  AuditLogExportResult,
  AuditRisk,
  CreateAuditLogInput,
  ListAuditLogsInput,
} from "./audit";
export type {
  CollectResourceBatchInput,
  CollectResourceBatchResult,
  KillMysqlQueryInput,
  KillMysqlQueryResult,
  ListResourceAlertEventsInput,
  ListResourceAlertRulesInput,
  MysqlSlowQuery,
  MysqlSlowQueryListInput,
  ResourceAlertEvent,
  ResourceAlertOperator,
  ResourceAlertRule,
  ResourceAlertSeverity,
  ResourceAlertStatus,
  ResourceMetricSnapshot,
  ResourceMonitorOverview,
  ResourceMonitorTarget,
  ResourceSnapshotListInput,
  ResourceStatus,
  ResourceTargetType,
  UpsertResourceAlertRuleInput,
  UpsertResourceMonitorTargetInput,
} from "./resourceMonitor";
export type {
  CreateDeploymentDryRunInput,
  CreateDeploymentRollbackDryRunInput,
  DeploymentAiAdviceInput,
  DeploymentAiAdviceResult,
  DeploymentCandidate,
  DeploymentDetectionResult,
  DeploymentEnvironmentProbe,
  DeploymentEnvironmentProfile,
  DeploymentGroup,
  DeploymentGroupTarget,
  DeploymentGroupTargetInput,
  DeploymentImageStoreApp,
  DeploymentImageStoreEnv,
  DeploymentPlan,
  DeploymentPlanStage,
  DeploymentProbeCheck,
  DeploymentRecipe,
  DeploymentRun,
  DeploymentRunDetail,
  DeploymentRunStep,
  DeploymentSourceType,
  DeploymentTarget,
  DeploymentTemplate,
  DetectDeploymentProjectInput,
  DockerBuildMode,
  ExecuteDeploymentRollbackInput,
  ExecuteDeploymentRunInput,
  InstallImageStoreAppInput,
  ListDeploymentRunsInput,
  UpsertDeploymentGroupInput,
  UpsertDeploymentTargetInput,
} from "./deployment";
export type {
  CleanupJenkinsArtifactInput,
  CreateJenkinsArtifactDeploymentCandidateInput,
  CreateJenkinsBuildDeploymentDryRunInput,
  DeleteJenkinsParameterTemplateInput,
  DownloadJenkinsArtifactInput,
  ExecuteJenkinsBuildApprovedInput,
  ExecuteJenkinsBuildStopApprovedInput,
  GenerateJenkinsFailureAnalysisInput,
  GetJenkinsBuildInput,
  GetJenkinsJobDetailInput,
  InspectJenkinsFileParameterInput,
  JenkinsArtifact,
  JenkinsBuild,
  JenkinsBuildAnalysis,
  JenkinsBuildLogInput,
  JenkinsBuildLogResult,
  JenkinsBuildStopResult,
  JenkinsBuildStatusEvent,
  JenkinsBuildTriggerResult,
  JenkinsConnection,
  JenkinsConnectionTestResult,
  JenkinsFileParameterMetadata,
  JenkinsJob,
  JenkinsJobDetail,
  JenkinsParameterDefinition,
  JenkinsParameterDefinitionsResult,
  JenkinsParameterTemplate,
  JenkinsQueueItem,
  JenkinsRecentParameterValue,
  JenkinsSensitiveParameterReference,
  ForgetJenkinsRecentParameterValueInput,
  ListJenkinsArtifactsInput,
  ListJenkinsBuildsInput,
  ListJenkinsConnectionsInput,
  ListJenkinsJobsInput,
  ListJenkinsParameterTemplatesInput,
  ListJenkinsParametersInput,
  ListJenkinsRecentParameterValuesInput,
  PollJenkinsQueueItemInput,
  RecordJenkinsLogCopyAuditInput,
  SetJenkinsJobFavoriteInput,
  StopJenkinsBuildInput,
  TriggerJenkinsBuildInput,
  UpsertJenkinsConnectionInput,
  UpsertJenkinsParameterTemplateInput,
  VerifyJenkinsParameterDefinitionHashInput,
} from "./jenkins";
